name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['927', '944'] # Not all dependencies support 9.6.1 yet
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    name: Build with GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: halide-haskell
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Halide test - dumping Exprs to ostream
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#testWriteExpr
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#ghc${{ matrix.ghc }}.halide-haskell
    - name: Examples & Tutorials
      run: |
        nix build --accept-flake-config --print-build-logs .#ghc${{ matrix.ghc }}.halide-all
