name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['925', '944']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Build with GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - name: Build
      run: |
        nix build \
          --accept-flake-config \
          --print-build-logs \
          .#ghc${{ matrix.ghc }}.halide-haskell
    - name: Examples & Tutorials
      run: |
        nix build --accept-flake-config --print-build-logs .#ghc${{ matrix.ghc }}.halide-readme
        nix build --accept-flake-config --print-build-logs .#ghc${{ matrix.ghc }}.halide-tutorial01
        nix build --accept-flake-config --print-build-logs .#ghc${{ matrix.ghc }}.halide-tutorial05
